apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  POSTGRES_DB: "project-postgresql-db"
  POSTGRES_HOST: "ahmed"
  POSTGRES_USER: "project-postgresql-server.postgres.database.azure.com"